### ISSUE TITLE
First motion polarity

### ISSUE THREAD

**Issue by Rinku-274** [uafgeotools/mtuq#170]
I am facing problem with attaching first motion polarity in MTUQ. Can you please provide a solution.

**Comment by rmodrak** [comment]
Hi Rinku-274, 

Welcome, thanks for raising this issue.  It seems like the polarity misfit function is sketched out, but not fully implemented.  It may be possible to use what's there now as starting point, if you're interested.  We will continuing working on it over the coming months, and when finished it will be documented [here](https://uafgeotools.github.io/mtuq/library/index.html).  Others may be able to comment further.

best wishes,
Ryan

**Comment by Rinku-274** [comment]
Thanks for your response. I am using MTUQ from last few months. It is quite helpful for me. Hope to see more features in future.

Best wishes,
Rinku

**Comment by thurinj** [comment]
Hi Rinku-274,

As Ryan mentioned, the functionality is here, but it is not yet fully developed to the same degree as the waveform misfit. Here is what you should do to perform a polarity-based grid search:

The relevant piece of code is located here  in [mtuq/misfit/polarity.py](https://github.com/uafgeotools/mtuq/blob/master/mtuq/misfit/polarity.py)
It currently relies on SAC headers (which will eventually not be a requirement as we improve on the current implementation).
You will need to assign to all of the obspy.traces you intent to use, the following header information if they are not currently filled in:
- `az` which should be the station Azimuth relative to the source
- `user3` which should contain the takeoff angle in a given model (assuming ak135 for instance).
To do so, I encourage you to use the last version of pysep (I just made a relevant update), and add the `ev_info.write_sac_phase = True` when setting up your event in the [pysep](https://github.com/uafgeotools/pysep) input file (`event_input.py `).

Otherwise you can manually add these information by doing the calculation yourself.

As for the `az` and `user3` SAC header fields, your observed polarity should go in the `user5` header field. 
Here an example of how this can be done:
```
In [1]: polarities
Out[1]:
array([ 1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  0,  1,  1,  0, -1,  0,  1,
       -1, -1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])
``` 
I've created a `polarities` array containing values, where `1` encodes a positive first motion, `-1` encodes for negative, and `0` for not picked. 
I then assign these picked values to my vertical traces:
```
#Loading only the vertical component of my data
path_data=    fullpath('data/examples/20210723042020000/*.[z]') 
path_weights= fullpath('data/examples/20210723042020000/weight.dat')
event_id=     '20210723042020000'
model=        'ak135'

station_id_list = parse_station_codes(path_weights)
data = read(path_data, format='sac',
    event_id=event_id,
    station_id_list=station_id_list,
    tags=['units:cm', 'type:velocity'])

#Assigning picked weights values from the polarities array to the user5 sac header
for _i, sta in enumerate(data):
    sta.select(channel='BHZ')[0].stats.sac['user5'] = polarities[_i]
```

The polarity misfit is initialized and computed this way:
```
pmisfit = PolarityMisfit()
results_polarity = grid_search(
        data, greens, pmisfit, origin, grid)

```
which supposes you have already opened your data and loaded Greens' function (they are actually not used in the misfit computation, hence this will change in the future as we improve this function). `grid` would be your typical DoubleCouple or FullMomentTensor grid.

The results_polarity will be a data structure (MTUQDataArray or MTUQDataFrame) containing the integer values counting the number of mismatching polarities for each source.

I will spend some time next week to refactor this function and make it more practical, as well as provide an example template to complement the waveform misfit currently included within the examples folder. You can go ahead and try this now or wait for a couple of days for my modifications.

**Comment by rmodrak** [comment]
Thanks for clarifying Julien.  Lots of useful details above.   It looks the formulas for predicted first motions are all there, which is a key thing.  With luck, we can decouple it a bit from sac headers.

**Comment by vsilwal** [comment]
Thanks Julien and Ryan for your suggestions. 

Rinku and I are not using pysep since the data is proprietary.

Since the take-off angle and azimuth are added in pysep, we will add an option in polarity.py to extract the take-off from the "user2" header of the fk green's function from (like in cap). Azimuth will have to be added separately. Also note that take-off angles in pysep are for ak135 model by default, and in green's function they will be for the particular local model. Another option is to populate the azimuth and take-off angle headers of data in your pre-processing script.

Observed polarity can be the input parameter in the weight file like it used to be.

I believe that the weight factor between polarity misfit and waveform misfit is also missing at the moment.

**Comment by rmodrak** [comment]
Hi Vipul,  

Good to hear from you and Rinku.   

Good point, attaching takeoff angles to the Green's functions makes sense, because as you were saying takeoff angles depend on the Earth model as well as the source location.

For reading takeoff angles from Green's functions databases or calculating them on the fly, one idea would be to exactly mimic the options that `ProcessData` uses for obtainting P and S traveltimes.  Currently, `ProcessData` can read read traveltimes from FK metadata or calculate them on the fly given the name of a builtin ObsPy taup model or the path to a custom ObsPy taup model.

It sounds like have the same goal of decoupling the source inversion and data acquisition codes.  In my case, we have a large investment in an Oracle database.  Instead of pysep or other approaches that write intermediate files to disk, we are encouraged to read from this database directly.

Ryan

**Comment by rmodrak** [comment]
For taking angle calculations--  as a starting point, we could mimic the on-the-fly approach used by [`plot_beachball`](https://uafgeotools.github.io/mtuq/library/generated/mtuq.graphics.plot_beachball.html)

**Comment by vsilwal** [comment]
Hi Ryan,

Also want to add it over here that we are using python based fk module [pyfk](https://github.com/ziyixi/pyfk/tree/ca473759a3a8b032b8e4f8194fa3cdbe4d75c9b2) (not fk.pl) Azimuth angle is estimated [here](https://github.com/ziyixi/pyfk/blob/ca473759a3a8b032b8e4f8194fa3cdbe4d75c9b2/pyfk/gf/gf.py#L57).

**Comment by rmodrak** [comment]
Thanks, Vipul

**Comment by thurinj** [comment]
Hi All,

Progress has been a bit slower than expected, but I am close to finishing the much-needed improvements on the polarity misfit implementation. I just published a new polarity_misfit branch with all the commits from this week.
The new function is now computing all the relevant quantities (azimuth, takeoff angles, theoretical radiation coefficient) on the fly from the green's function list. It requires pointing toward the appropriate osbpy taup velocity model (.npz file) and will get the takeoff angle directly out of the green's function SAC header `user1` field if reading from an FK database. 

The polarity misfit now accepts various input types :

- List or numpy array containing observed polarities (1, 0, -1), of the length of the green's tensor list
- mtuq Database with properly pre-set sac header, allowing to use and change any custom sac header field.
- mtuq GreensTensorList with properly pre-set sac header, also allowing to use and change any custom sac header field.
- a path to the weight.dat file, to accept CAPUAF-like polarity inputs (`NETWORK.STATION/+1` or `NETWORK.STATION/-1`). The lines without a `/value` will be counted as `/0`.

I would recommend using the list/array input and weight file input at the moment, as I continue to iterate on the implementation for the Database and GreensTensorList header inputs.
The misfit function will figure out automatically how to extract the polarity values from the various accepted input type. 

As for your comment Vipul:
> I believe that the weight factor between polarity misfit and waveform misfit is also missing at the moment.

As of now, I am not sure this will be implemented, as it might not be needed. The current design philosophy of the code is to allow as much flexibility as possible to users when defining the misfit, such that it is possible to carry out any required operation on the separate instances of misfit results (body, surface waves, polarity, Love and Rayleigh...).
For instance, equation (1) from[Alvizuri, et al., 2018](https://drive.google.com/file/d/1q688mVmuMnir3967eaWAraK4mnGWLQ72/view) could easily be recreated this way with basic operations on the misfits:
```
polarity_result = grid_search(polarity_input, greens, polarity_misfit, origin, grid)
bw_result = grid_search(data_bw, greens_bw, misfit_bw, origin, grid)
sw_result = grid_search(data_sw, greens_sw, misfit_sw, origin, grid)

total_results = m*polarity_result/sum(abs(polarity_input)) + (1-m)*(bw_result+ sw_result)
```
This way, any type of misfit combination is possible, without the need for a dedicated function. This will also allow testing various misfit formulas on the fly as a post-processing procedure.

I aim to finalize and refine the implementation of the misfit function and plotting tools (that have been refactored accordingly) sometime early next week. There is still some work to do, notably in providing a template example for polarity misfit but also completing all the new functions docstrings.  As soon as I am done, I'll initiate a pull request so that you can step in and suggest changes / review the new implementation!

Thanks again for your suggestions and remarks !

**Comment by rmodrak** [comment]
Just a heads up that the polarity misfit function is still under development, and additional API changes are likely.  Hoping to iterate this summer on Julien's changes, which were a major step forward.

In particular, changes are need to ensure file format independence. [Here](https://github.com/rmodrak/mtuq/blob/d36fba83dda8aa2afd4aa7527a42a8b8f18ed8ad/mtuq/process_data.py#L368) is one example a a line that breaks file format independence and causes my scripts to fail.

**Comment by rmodrak** [comment]
@thurinj, @carltape: The following changes are included in the latest pull request

- I tried refactoring the polarity misfit function. The new version is easier to follow I think and improves certain fragile aspects

- By reducing use of SAC headers, it is now possible in principle to make polarity measurements on waveforms from wfdisk databases or other source

- The new example `Waveforms+Polarities.py` returns the same misfit surface as before but otherwise replaces the old example

- The polarity option for `beachball_pygmt.py` is now likely broken.  I will get around to fixing at some point, or someone else can make an attempt.  Please try to make these changes via `beachball.py` (see `plot_polarities()` and other stubs)

- The functions for calculating polarities from an FK database still need to be double checked

**Comment by carltape** [comment]
Thanks, Ryan. We'll discuss this next week. Great to see polarity capabilities in the mix; we'll try to keep the plotting capabilities working.

**Comment by rmodrak** [comment]
In the latest pull request, believe the polarity misfit function and beachball plotting utilities are now both fully working
