### ISSUE TITLE
Inversion depth at model interface

### ISSUE THREAD

**Issue by vsilwal** [uafgeotools/mtuq#192]
It looks like mtuq continues to crashes when the event lies at the model interface. 
To avoid this, we generally change the inversion depth by +-1 km. In original version of CAP this was handled directly during inversion, however, in mtuq this requires changing the SAC headers.
I believe this capability should be available in mtuq.

**Comment by rmodrak** [comment]
To work around gaps in an FK database, you could change the origin depth that gets passed to the database query.  (For example, change [here](https://github.com/uafgeotools/mtuq/blob/8ec57dc8654ebd9d98bf65b5e50c03e1f71511d9/examples/GridSearch.DoubleCouple.py#L120)).

I think a more helpful error message could probably be useful here, but aside from that a good solution doesn't really come to mind.   FK directory structures provide no way to distinguish between gaps due to layer interfaces versus simple incompleteness?  Celso's databases often had the latter.

**Comment by rmodrak** [comment]
One idea-- we could add some type of error handling to check if the Green's functions exist immediately above and below the specified depth.  If so, the gap likely corresponds to a layer interface.  And then, rather than trying to interpolate across the interface, we should just return an error message with a suggestion to choose a slightly different origin depth?

**Comment by vsilwal** [comment]
Changes the depth here: https://github.com/uafgeotools/mtuq/blob/8ec57dc8654ebd9d98bf65b5e50c03e1f71511d9/examples/GridSearch.DoubleCouple.py#L120
is not reflected in the solution. mtuq still takes depth from the SAC headers. 
For now we will fix the headers, and plan for a fix for this and submit a pull request.

**Comment by rmodrak** [comment]
In general, you can just change the database query, without any need to change the sac headers.  

for example, in the [mtuq/examples/GridSearch.DoubleCouple.py](https://github.com/uafgeotools/mtuq/blob/8ec57dc8654ebd9d98bf65b5e50c03e1f71511d9/examples/GridSearch.DoubleCouple.py#L120) example just mentioned, the value in line 120 gets passed to the database query in line line 150.

**Comment by ammcpherson** [comment]
Hi @vsilwal,

I am pretty certain that you are talking about the same issue that I raised [back in October](https://github.com/uafgeotools/mtuq/issues/184). At the bottom of the thread is a working example of how to work around this problem.
