### ISSUE TITLE
Error when using download_greens_tensors(stations, origin, model)

### ISSUE THREAD

**Issue by CSUPZW** [uafgeotools/mtuq#242]
When running 
"print('Reading Greens functions...\n')
 greens = download_greens_tensors(stations, origin, model)"  
in "GridSearch.DoubleCouple.py",  it shows:
FileNotFoundError: [Errno 2] No such file or directory: '../mtuq/lib/python3.12/site-packages/mtuq-0.2.0-py3.12-linux-x86_64.egg/data/greens_tensor/syngine/cache/d70a6108-2982-5849-b885-b9a8cffacd8d.zip'

**Comment by thurinj** [comment]
Hi @CSUPZW ,

Have you been able to download any GF at all previous to this error? 
- If not, and this is the first time to attempt downloading GFs, could this be an problem with writing the files on your mtuq directory?

- If yes, and this is coming up from the first time, it might be coming from an interrupted download or a corrupted file in the cached GFs. You could go and check in your `mtuq-0.2.0-py3.12-linux-x86_64.egg/data/greens_tensor/syngine/cache/` folder, and perhaps remove the most recent set of downloaded green's functions? One clue that something might have gone wrong is if the last downloaded zip file is smaller that what you would expect.

I hope this helps.

**Comment by rmodrak** [comment]
It seems like the FileNotFound error may result from a non-editable
installation or otherwise unwritable path.

You can specify a different download path via the SYNGINE_CACHE environment
value
https://github.com/uafgeotools/mtuq/blob/d7d53e38995ed86a7082861987efa85c2e9f6127/mtuq/util/syngine.py#L80

Or install mtuq in editable mode using "pip install -e".

**Comment by CSUPZW** [comment]
Thanks for your help. I install mtuq in editable mode again and the error is solved.
